#!/bin/bash

# Build script for Threads Native App for macOS
# This script should be run on macOS

echo -e "\033[36mBuilding Threads Native App for macOS...\033[0m"

# Check if Python 3 is installed
if ! command -v python3 &> /dev/null; then
    echo -e "\033[31mError: Python 3 is not installed\033[0m"
    echo -e "\033[33mPlease install Python 3 from https://www.python.org/downloads/\033[0m"
    exit 1
fi

PYTHON_VERSION=$(python3 --version)
echo -e "\033[32mFound $PYTHON_VERSION\033[0m"

# Create virtual environment if it doesn't exist
if [ ! -d "venv" ]; then
    echo -e "\n\033[33mCreating virtual environment...\033[0m"
    python3 -m venv venv
fi

# Activate virtual environment
source venv/bin/activate

# Install dependencies
echo -e "\n\033[33mInstalling dependencies...\033[0m"
pip install --upgrade pip
pip install pywebview py2app

if [ $? -ne 0 ]; then
    echo -e "\033[31mError: Failed to install dependencies\033[0m"
    exit 1
fi

# Create setup.py if it doesn't exist
if [ ! -f "setup.py" ]; then
    echo -e "\n\033[33mCreating setup.py for macOS build...\033[0m"
    cat > setup.py << 'EOF'
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['threads-app.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'LSUIElement': False,
        'CFBundleName': 'Threads',
        'CFBundleDisplayName': 'Threads',
        'CFBundleIdentifier': 'com.threads.native-app',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'NSHumanReadableCopyright': 'Threads Native App',
        'NSRequiresAquaSystemAppearance': False,  # Support dark mode
    },
    'packages': ['webview'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
EOF
fi

# Clean previous builds
echo -e "\n\033[33mCleaning previous builds...\033[0m"
rm -rf build dist

# Build the app
echo -e "\n\033[33mBuilding macOS app...\033[0m"
python setup.py py2app

if [ $? -ne 0 ]; then
    echo -e "\033[31mError: Failed to build app\033[0m"
    exit 1
fi

# Check if build was successful
if [ -d "dist/Threads.app" ]; then
    echo -e "\n\033[32mBuild successful!\033[0m"
    echo -e "\033[36mApp location: ./dist/Threads.app\033[0m"
    
    # Ask if user wants to move to Applications
    echo -e "\n\033[33mMove Threads.app to Applications folder? (y/n)\033[0m"
    read -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        cp -r dist/Threads.app /Applications/
        echo -e "\033[32mThreads.app has been installed to /Applications\033[0m"
    fi
    
    # Ask if user wants to run the app
    echo -e "\n\033[33mRun Threads app now? (y/n)\033[0m"
    read -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        open dist/Threads.app
    fi
else
    echo -e "\033[31mError: App bundle not found in dist folder\033[0m"
    exit 1
fi

echo -e "\n\033[32mDone!\033[0m"