"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['threads-app.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'LSUIElement': False,
        'CFBundleName': 'Threads',
        'CFBundleDisplayName': 'Threads',
        'CFBundleIdentifier': 'com.threads.native-app',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'NSHumanReadableCopyright': 'Threads Native App',
        'NSRequiresAquaSystemAppearance': False,  # Support dark mode
    },
    'packages': ['webview'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)