"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['threads-app.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,  # Disable argv_emulation to avoid code signing issues
    'plist': {
        'LSUIElement': False,
        'CFBundleName': 'Threads',
        'CFBundleDisplayName': 'Threads',
        'CFBundleIdentifier': 'com.threads.native-app',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'NSHumanReadableCopyright': 'Threads Native App',
        'NSRequiresAquaSystemAppearance': False,  # Support dark mode
        'NSHighResolutionCapable': True,
    },
    'packages': ['webview', 'objc', 'Foundation', 'AppKit', 'WebKit', 'CoreFoundation'],
    'includes': ['WebKit', 'Foundation', 'AppKit', 'objc', 'objc._objc'],
    'arch': 'arm64',  # Specify architecture explicitly
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)